### ISSUE TITLE
カスタムしたReleasesを作成する方法に関して記述する

### ISSUE THREAD

**Issue by RyosukeDTomita** [RyosukeDTomita/react-roulette-frontend#41]
### New feature description
Releasesをタグ切った際にカスタムzipを作成して配置する。

### background
- Releasesを使ってみたい

### solution

```
name: create zip for user document upload script
on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

jobs:
  create_published:
    runs-on: ubuntu-latest

    steps:
      - name: clone application source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: create zip
        run: zip -r aoai.zip .azure scripts

      - name: upload Releases
        uses: shogo82148/actions-upload-release-asset@8f032eff0255912cc9c8455797fd6d72f25c7ab7 # v1.7.5
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: aoai.zip
          asset_name: aoai.zip

```
